// <auto-generated />
using System;
using Infrastructure.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(BotDbContext))]
    partial class BotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Bot.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Step")
                        .HasColumnType("integer");

                    b.Property<string>("StepData")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Step = 0,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.Bot.BotMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Command")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BotMessages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Command = 1,
                            Message = "پیام کامند استارت"
                        },
                        new
                        {
                            Id = 10,
                            Command = 10,
                            Message = "به منوی اصلی بازگشتید"
                        },
                        new
                        {
                            Id = 2,
                            Command = 2,
                            Message = "پیام خرید سرویس - مرحله انتخاب سرویس"
                        },
                        new
                        {
                            Id = 3,
                            Command = 3,
                            Message = "پیام تمدید سرویس - مرحله انتخاب سرویس جهت تمدید"
                        },
                        new
                        {
                            Id = 4,
                            Command = 4,
                            Message = "پیام سرویس های من - مرحله نمایش سرویس ها"
                        },
                        new
                        {
                            Id = 5,
                            Command = 5,
                            Message = "حجم اضافه - انتخاب سرویس جهت افزودن حجم"
                        },
                        new
                        {
                            Id = 6,
                            Command = 6,
                            Message = "TextMessage-PlansMessage"
                        },
                        new
                        {
                            Id = 7,
                            Command = 7,
                            Message = "پیام کیف پول - نمایش بالانس"
                        },
                        new
                        {
                            Id = 8,
                            Command = 8,
                            Message = "پیام پشتیبانی - نمایش ایدی اکانت پشتیبانی"
                        },
                        new
                        {
                            Id = 9,
                            Command = 9,
                            Message = "پیام راهنما"
                        },
                        new
                        {
                            Id = 14,
                            Command = 14,
                            Message = "نام نمایشی: <TITLE>\r\nسرویس: <SERVICE>\r\nوضعیت: <STATUS>\r\nیادداشت: <NOTE>"
                        },
                        new
                        {
                            Id = 15,
                            Command = 15,
                            Message = "سرویس انتخاب شده - وارد کردن حجم"
                        },
                        new
                        {
                            Id = 16,
                            Command = 16,
                            Message = "سرویس انتخاب شده جهت تمدید - تعداد ماه"
                        },
                        new
                        {
                            Id = 17,
                            Command = 17,
                            Message = "شارژ ولت انتخاب شده - وارد کردن مبلغ"
                        },
                        new
                        {
                            Id = 18,
                            Command = 18,
                            Message = "مبلغ وارد شده: <AMOUNT>\r\nروش پرداخت را انتخاب کنید:"
                        },
                        new
                        {
                            Id = 19,
                            Command = 19,
                            Message = "روش پرداخت: کارت به کارت\r\nمبلغ: <code><AMOUNT></code>\r\nشماره کارت: <code><CARD></code>\r\nبه شماره کارت بالا واریز کنید و رسید بفرستید"
                        },
                        new
                        {
                            Id = 11,
                            Command = 11,
                            Message = "سرویس انتخاب شده: <NAME>\r\nانتخاب مدت زمان سرویس:"
                        },
                        new
                        {
                            Id = 12,
                            Command = 12,
                            Message = "سرویس انتخاب شده: <NAME>\r\nمدت زمان سرویس: <MONTH>\r\nانتخاب ترافیک:"
                        },
                        new
                        {
                            Id = 13,
                            Command = 13,
                            Message = "سرویس انتخاب شده: <NAME>\r\nمدت زمان سرویس: <MONTH>\r\nمقدار ترافیک: <TRAFFIC>\r\nمبلغ نهایی: <PRICE>\r\nفاکتور ساخته شد ، انتخاب روش پرداخت: "
                        });
                });

            modelBuilder.Entity("Domain.Entities.Bot.BotSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BotSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "DOMAIN",
                            Value = "https://library98.ir/"
                        },
                        new
                        {
                            Id = 2,
                            Key = "STATUS",
                            Value = "1"
                        },
                        new
                        {
                            Id = 3,
                            Key = "MIN_AMOUNT",
                            Value = "50000"
                        },
                        new
                        {
                            Id = 4,
                            Key = "MAX_AMOUNT",
                            Value = "500000"
                        },
                        new
                        {
                            Id = 5,
                            Key = "RECEIPT_CHATID",
                            Value = "-1002583876730"
                        },
                        new
                        {
                            Id = 6,
                            Key = "CARD",
                            Value = "0000000000000000"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Bot.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("Domain.Entities.Bot.Factor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("UniqueKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserSubscriptionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserSubscriptionId");

                    b.ToTable("Factors");
                });

            modelBuilder.Entity("Domain.Entities.Bot.MonthPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<int>("PricePerMonth")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MonthPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Month = 1,
                            PricePerMonth = 5000
                        },
                        new
                        {
                            Id = 2,
                            Month = 3,
                            PricePerMonth = 3000
                        },
                        new
                        {
                            Id = 3,
                            Month = 6,
                            PricePerMonth = 2000
                        });
                });

            modelBuilder.Entity("Domain.Entities.Bot.TrafficPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Bandwidth")
                        .HasColumnType("integer");

                    b.Property<int>("MonthPlanId")
                        .HasColumnType("integer");

                    b.Property<int>("PricePerGb")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MonthPlanId");

                    b.ToTable("TrafficPlans");

                    b.HasData(
                        new
                        {
                            Id = 7,
                            Bandwidth = 150,
                            MonthPlanId = 3,
                            PricePerGb = 2000
                        },
                        new
                        {
                            Id = 8,
                            Bandwidth = 200,
                            MonthPlanId = 3,
                            PricePerGb = 1800
                        },
                        new
                        {
                            Id = 9,
                            Bandwidth = 450,
                            MonthPlanId = 3,
                            PricePerGb = 1500
                        },
                        new
                        {
                            Id = 4,
                            Bandwidth = 30,
                            MonthPlanId = 2,
                            PricePerGb = 2750
                        },
                        new
                        {
                            Id = 5,
                            Bandwidth = 60,
                            MonthPlanId = 2,
                            PricePerGb = 2650
                        },
                        new
                        {
                            Id = 6,
                            Bandwidth = 90,
                            MonthPlanId = 2,
                            PricePerGb = 2500
                        },
                        new
                        {
                            Id = 1,
                            Bandwidth = 15,
                            MonthPlanId = 1,
                            PricePerGb = 3000
                        },
                        new
                        {
                            Id = 2,
                            Bandwidth = 30,
                            MonthPlanId = 1,
                            PricePerGb = 2850
                        },
                        new
                        {
                            Id = 3,
                            Bandwidth = 45,
                            MonthPlanId = 1,
                            PricePerGb = 2750
                        });
                });

            modelBuilder.Entity("Domain.Entities.Bot.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DiscountId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<int>("Step")
                        .HasColumnType("integer");

                    b.Property<string>("StepData")
                        .HasColumnType("text");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DiscountId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Main",
                            JoinDate = new DateTime(2025, 4, 15, 17, 59, 3, 515, DateTimeKind.Utc).AddTicks(3298),
                            LastName = "Admin",
                            Step = 0,
                            StepData = "",
                            UserId = 7880935437L,
                            Username = "MrMorphling"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Bot.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Balance")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("Domain.Entities.Vpn.ApiInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ApiInfos");
                });

            modelBuilder.Entity("Domain.Entities.Vpn.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Domain.Entities.Vpn.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Bandwidth")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpireTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ServiceId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersSubscriptions");
                });

            modelBuilder.Entity("Domain.Entities.Bot.Admin", b =>
                {
                    b.HasOne("Domain.Entities.Bot.User", "User")
                        .WithOne("Admin")
                        .HasForeignKey("Domain.Entities.Bot.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Bot.Factor", b =>
                {
                    b.HasOne("Domain.Entities.Bot.User", "User")
                        .WithMany("UserFactors")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Vpn.UserSubscription", "UserSubscription")
                        .WithMany()
                        .HasForeignKey("UserSubscriptionId");

                    b.Navigation("User");

                    b.Navigation("UserSubscription");
                });

            modelBuilder.Entity("Domain.Entities.Bot.TrafficPlan", b =>
                {
                    b.HasOne("Domain.Entities.Bot.MonthPlan", "MonthPlan")
                        .WithMany("TrafficPlans")
                        .HasForeignKey("MonthPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonthPlan");
                });

            modelBuilder.Entity("Domain.Entities.Bot.User", b =>
                {
                    b.HasOne("Domain.Entities.Bot.Discount", "Discount")
                        .WithMany("Users")
                        .HasForeignKey("DiscountId");

                    b.Navigation("Discount");
                });

            modelBuilder.Entity("Domain.Entities.Bot.Wallet", b =>
                {
                    b.HasOne("Domain.Entities.Bot.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("Domain.Entities.Bot.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Vpn.UserSubscription", b =>
                {
                    b.HasOne("Domain.Entities.Vpn.Service", "Service")
                        .WithMany("UsersSubscriptions")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Bot.User", "User")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Bot.Discount", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Bot.MonthPlan", b =>
                {
                    b.Navigation("TrafficPlans");
                });

            modelBuilder.Entity("Domain.Entities.Bot.User", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("UserFactors");

                    b.Navigation("UserSubscriptions");

                    b.Navigation("Wallet")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Vpn.Service", b =>
                {
                    b.Navigation("UsersSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
